/**
 * Agent installer script generation.
 *
 * Two delivery shapes share one script body:
 *
 *   /q/:token        token embedded in the URL — for copy-paste installs from
 *                    the admin UI.
 *   /install/:os     token supplied via the WMS_ENROLL_TOKEN environment
 *                    variable — for SSH push-deploy, which exports the token
 *                    and pipes through `sudo -E bash`.
 */

export interface InstallerOptions {
  /** Embedded enrollment token, or null to read WMS_ENROLL_TOKEN from the env. */
  token:      string | null;
  serverBase: string;
  wsUrl:      string;
}

export function bashInstaller({ token, serverBase, wsUrl }: InstallerOptions): string {
  // With an embedded token the script pins it; otherwise it requires the
  // caller to have exported it (and fails loudly if they did not).
  const tokenLine = token
    ? `WMS_TOKEN="${token}"`
    : `WMS_TOKEN="\${WMS_ENROLL_TOKEN:?WMS_ENROLL_TOKEN not set — export it before piping this script to bash}"`;

  const serverLine = token
    ? `WMS_SERVER="${serverBase}"`
    : `WMS_SERVER="\${WMS_SERVER_BASE:-${serverBase}}"`;

  const wsLine = token
    ? `WMS_WS="${wsUrl}"`
    : `WMS_WS="\${WMS_SERVER_URL:-${wsUrl}}"`;

  return `#!/usr/bin/env bash
# WMS Agent — installer
# Generated by WorkstationMonSys.
set -euo pipefail

${tokenLine}
${serverLine}
${wsLine}
INSTALL_DIR="/usr/local/bin"
STATE_DIR="/etc/wms-agent"
BINARY="wms-agent"

echo "==> WorkstationMonSys Agent Installer"
echo "    Server : $WMS_SERVER"

OS="\$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="\$(uname -m)"
case "\$ARCH" in
  x86_64)  ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) echo "Unsupported arch: \$ARCH"; exit 1 ;;
esac

echo "    Platform: \$OS-\$ARCH"

# ── Download pre-built binary ─────────────────────────────────────────────
DOWNLOAD_URL="\$WMS_SERVER/download/wms-agent-\$OS-\$ARCH"
echo "==> Downloading agent binary..."
if command -v curl &>/dev/null; then
  curl -fsSL "\$DOWNLOAD_URL" -o "/tmp/\$BINARY"
elif command -v wget &>/dev/null; then
  wget -qO "/tmp/\$BINARY" "\$DOWNLOAD_URL"
else
  echo "ERROR: curl or wget required"; exit 1
fi
chmod +x "/tmp/\$BINARY"

sudo mkdir -p "\$STATE_DIR" "\$INSTALL_DIR"
sudo mv "/tmp/\$BINARY" "\$INSTALL_DIR/\$BINARY"
echo "    Installed: \$INSTALL_DIR/\$BINARY"

# ── Install as system service ─────────────────────────────────────────────
if [ "\$OS" = "darwin" ]; then
  PLIST_DIR="/Library/LaunchDaemons"
  PLIST_LABEL="com.wms.agent"
  sudo tee "\$PLIST_DIR/\$PLIST_LABEL.plist" > /dev/null <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key>             <string>\$PLIST_LABEL</string>
  <key>ProgramArguments</key>  <array><string>\$INSTALL_DIR/\$BINARY</string></array>
  <key>EnvironmentVariables</key><dict>
    <key>WMS_SERVER_URL</key>  <string>\$WMS_WS</string>
    <key>WMS_ENROLL_TOKEN</key><string>\$WMS_TOKEN</string>
    <key>WMS_STATE_FILE</key>  <string>\$STATE_DIR/state.json</string>
    <key>WMS_INTERVAL</key>    <string>10s</string>
  </dict>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/var/log/wms-agent.log</string>
  <key>StandardErrorPath</key><string>/var/log/wms-agent.log</string>
</dict></plist>
PLIST
  sudo launchctl unload "\$PLIST_DIR/\$PLIST_LABEL.plist" 2>/dev/null || true
  sudo launchctl load   "\$PLIST_DIR/\$PLIST_LABEL.plist"
  echo "==> Agent installed as launchd service."
  echo "    Logs: sudo tail -f /var/log/wms-agent.log"

else
  # Linux — systemd
  sudo tee /etc/systemd/system/wms-agent.service > /dev/null <<SERVICE
[Unit]
Description=WMS Monitoring Agent
After=network.target

[Service]
ExecStart=\$INSTALL_DIR/\$BINARY
Environment=WMS_SERVER_URL=\$WMS_WS
Environment=WMS_ENROLL_TOKEN=\$WMS_TOKEN
Environment=WMS_STATE_FILE=\$STATE_DIR/state.json
Environment=WMS_INTERVAL=10s
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICE
  sudo systemctl daemon-reload
  sudo systemctl enable --now wms-agent
  echo "==> Agent installed as systemd service."
  echo "    Logs: journalctl -u wms-agent -f"
fi
`;
}

export function powershellInstaller({ token, serverBase, wsUrl }: InstallerOptions): string {
  const tokenLine = token
    ? `$Token  = "${token}"`
    : `$Token  = if ($env:WMS_ENROLL_TOKEN) { $env:WMS_ENROLL_TOKEN } else { throw "WMS_ENROLL_TOKEN not set" }`;

  return [
    `# WMS Agent installer — Windows PowerShell`,
    `$ErrorActionPreference = "Stop"`,
    tokenLine,
    `$Server = "${serverBase}"`,
    `$WsUrl  = "${wsUrl}"`,
    `$Dir    = "C:\\wms-agent"`,
    `$Binary = "wms-agent.exe"`,
    ``,
    `Write-Host "==> WorkstationMonSys Agent Installer"`,
    `New-Item -ItemType Directory -Force $Dir | Out-Null`,
    `Write-Host "==> Downloading agent binary..."`,
    `Invoke-WebRequest -Uri "$Server/download/wms-agent-windows-amd64.exe" -OutFile "$Dir\\$Binary" -UseBasicParsing`,
    `$action   = New-ScheduledTaskAction -Execute "$Dir\\$Binary"`,
    `$trigger  = New-ScheduledTaskTrigger -AtStartup`,
    `$settings = New-ScheduledTaskSettingsSet -RestartInterval (New-TimeSpan -Seconds 10) -RestartCount 999`,
    `$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest`,
    `$task = New-ScheduledTask -Action $action -Trigger $trigger -Settings $settings -Principal $principal`,
    `Register-ScheduledTask -TaskName "WMSAgent" -InputObject $task -Force | Out-Null`,
    `[System.Environment]::SetEnvironmentVariable("WMS_SERVER_URL",   $WsUrl, "Machine")`,
    `[System.Environment]::SetEnvironmentVariable("WMS_ENROLL_TOKEN", $Token, "Machine")`,
    `[System.Environment]::SetEnvironmentVariable("WMS_STATE_FILE",   "$Dir\\state.json", "Machine")`,
    `[System.Environment]::SetEnvironmentVariable("WMS_INTERVAL",     "10s", "Machine")`,
    `Start-ScheduledTask -TaskName "WMSAgent"`,
    `Write-Host "==> Agent installed and running."`,
  ].join("\r\n");
}
